---
- hosts: volume-nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
  - volumes
  roles:
    - role: volumes/kong
    - role: volumes/minio
    - role: volumes/mongodb
    - role: volumes/postgres
    - role: volumes/prometheus
    - role: volumes/kafka-ws
    - role: volumes/kafka
    - role: volumes/zookeeper
    - role: volumes/ejbca
    - role: volumes/influxdb

- hosts: master_nodes
  gather_facts: true
  any_errors_fatal: true
  tags:
  - volumes
  roles:
    - role: volumes/labels
    - role: volumes/kong
    - role: volumes/minio
    - role: volumes/mongodb
    - role: volumes/postgres
    - role: volumes/prometheus
    - role: volumes/kafka-ws
    - role: volumes/kafka
    - role: volumes/zookeeper
    - role: volumes/ejbca
    - role: volumes/influxdb