---
all:
  hosts:
    localhost:
        ansible_connection: local
        ansible_python.version.major: 3
    nginx:
        ansible_host: NGINX_HOST_ADDRESS #change to the host of NGINX
  children:
    dojot-k8s:
      hosts:
        localhost:
    apigw_nodes:
      hosts:
        APIGW_HOST_ADDRESS: #change to the host of API GW worker node on k8s
    mqtt_nodes:
      hosts:
        MQTT_HOST_ADDRESS: #change to the host of MQTT worker node on k8s
    lwm2m_nodes:
      hosts:
        LWM2M_HOST_ADDRESS: #change to the host of LWM2M worker node on k8s
    metrics_nodes:
      hosts:
        METRICS_HOST_ADDRESS: #change to the host of Metrics worker node on k8s