# Set the dojot deployment namesapce
dojot_namespace: dojot

dojot_version: v0.4.4-rc.1

dojot_domain_name: localhost

dojot_storage_class_name: ""

# Set kubernetes RBAC
dojot_kubernetes_rbac: true

# Set dojot configurations for Zookeeper
dojot_zk_persistent_volumes: false

# Set dojot configuration for postgreSQL
dojot_psql_persistent_volumes: false

# Set dojot configuration for mongoDB
dojot_mongodb_persistent_volumes: false

# Set Minio configuration for dojot
dojot_minio_persistent_volumes: false

# Set Kafka configuration for dojot
dojot_kafka_persistent_volumes: false

# Set auth configuration
dojot_auth_email_enabled: false

# Allow the usage of insecure mqtt
dojot_insecure_mqtt: 'true'

# Set dojot docnfiguration for EJBCA
dojot_ejbca_persistent_volumes: false

# Enables fixed nodeports
dojot_fixed_nodeports_enabled: false


# Fixed nodeports to use. It's used if dojot_fixed_nodeports_enabled is true
dojot_nodeports:
  apigw:
    http: 30001
  mqtt: 30004
  mqtts: 30005
  lwm2m:
    coap: 30006
    coaps: 30007
    file_server: 30008
    file_servers: 30009
    http: 30010